
import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jovan Milutinovic
 */
public class Tastatura extends javax.swing.JFrame {

    /**
     * Creates new form Tastatura
     */
    public Tastatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        e = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        q = new javax.swing.JButton();
        w = new javax.swing.JButton();
        u = new javax.swing.JButton();
        r = new javax.swing.JButton();
        t = new javax.swing.JButton();
        y = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        i = new javax.swing.JButton();
        o = new javax.swing.JButton();
        p = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        d = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        a = new javax.swing.JButton();
        s = new javax.swing.JButton();
        j = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        k = new javax.swing.JButton();
        l = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        c = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        z = new javax.swing.JButton();
        x = new javax.swing.JButton();
        m = new javax.swing.JButton();
        v = new javax.swing.JButton();
        b = new javax.swing.JButton();
        n = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        capslockOznaka = new javax.swing.JLabel();
        capslockOznaka1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tastatura");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1110, 60));

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("3");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 60, 40));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setText("`");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 40));

        jButton3.setBackground(new java.awt.Color(51, 0, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("1");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, 40));

        jButton4.setBackground(new java.awt.Color(51, 0, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("2");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 60, 40));

        jButton5.setBackground(new java.awt.Color(51, 0, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("7");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 60, 40));

        jButton6.setBackground(new java.awt.Color(51, 0, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("4");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 60, 40));

        jButton7.setBackground(new java.awt.Color(51, 0, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("5");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 60, 40));

        jButton8.setBackground(new java.awt.Color(51, 0, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("6");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 60, 40));

        jButton9.setBackground(new java.awt.Color(0, 255, 0));
        jButton9.setText("=");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 60, 40));

        jButton10.setBackground(new java.awt.Color(51, 0, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("8");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 60, 40));

        jButton11.setBackground(new java.awt.Color(51, 0, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("9");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 60, 40));

        jButton12.setBackground(new java.awt.Color(51, 0, 255));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("0");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 60, 40));

        jButton13.setBackground(new java.awt.Color(0, 255, 0));
        jButton13.setText("/");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 90, 60, 40));

        jButton14.setBackground(new java.awt.Color(0, 255, 0));
        jButton14.setText("-");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 60, 40));

        jButton15.setBackground(new java.awt.Color(0, 255, 0));
        jButton15.setText("+");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 60, 40));

        jButton16.setBackground(new java.awt.Color(0, 255, 0));
        jButton16.setText("*");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 60, 40));

        e.setBackground(new java.awt.Color(153, 0, 153));
        e.setForeground(new java.awt.Color(255, 255, 255));
        e.setText("E");
        e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eMouseClicked(evt);
            }
        });
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 60, 40));

        jButton18.setBackground(new java.awt.Color(255, 0, 0));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("tab");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 40));

        q.setBackground(new java.awt.Color(153, 0, 153));
        q.setForeground(new java.awt.Color(255, 255, 255));
        q.setText("Q");
        q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qMouseClicked(evt);
            }
        });
        getContentPane().add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, 40));

        w.setBackground(new java.awt.Color(153, 0, 153));
        w.setForeground(new java.awt.Color(255, 255, 255));
        w.setText("W");
        w.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wMouseClicked(evt);
            }
        });
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });
        getContentPane().add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 60, 40));

        u.setBackground(new java.awt.Color(153, 0, 153));
        u.setForeground(new java.awt.Color(255, 255, 255));
        u.setText("U");
        u.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uMouseClicked(evt);
            }
        });
        getContentPane().add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 60, 40));

        r.setBackground(new java.awt.Color(153, 0, 153));
        r.setForeground(new java.awt.Color(255, 255, 255));
        r.setText("R");
        r.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rMouseClicked(evt);
            }
        });
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 60, 40));

        t.setBackground(new java.awt.Color(153, 0, 153));
        t.setForeground(new java.awt.Color(255, 255, 255));
        t.setText("T");
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
        });
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 60, 40));

        y.setBackground(new java.awt.Color(153, 0, 153));
        y.setForeground(new java.awt.Color(255, 255, 255));
        y.setText("Y");
        y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yMouseClicked(evt);
            }
        });
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });
        getContentPane().add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 60, 40));

        jButton25.setBackground(new java.awt.Color(0, 255, 0));
        jButton25.setText("[");
        jButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton25MouseClicked(evt);
            }
        });
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, 60, 40));

        i.setBackground(new java.awt.Color(153, 0, 153));
        i.setForeground(new java.awt.Color(255, 255, 255));
        i.setText("I");
        i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iMouseClicked(evt);
            }
        });
        getContentPane().add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 60, 40));

        o.setBackground(new java.awt.Color(153, 0, 153));
        o.setForeground(new java.awt.Color(255, 255, 255));
        o.setText("O");
        o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oMouseClicked(evt);
            }
        });
        getContentPane().add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 60, 40));

        p.setBackground(new java.awt.Color(153, 0, 153));
        p.setForeground(new java.awt.Color(255, 255, 255));
        p.setText("P");
        p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMouseClicked(evt);
            }
        });
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 60, 40));

        jButton29.setBackground(new java.awt.Color(0, 255, 0));
        jButton29.setText("*");
        jButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton29MouseClicked(evt);
            }
        });
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 60, 40));

        jButton30.setBackground(new java.awt.Color(0, 255, 0));
        jButton30.setText("]");
        jButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton30MouseClicked(evt);
            }
        });
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 60, 40));

        jButton31.setBackground(new java.awt.Color(0, 255, 0));
        jButton31.setText("\\");
            jButton31.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton31MouseClicked(evt);
                }
            });
            getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 60, 40));

            jButton32.setBackground(new java.awt.Color(0, 255, 0));
            jButton32.setText("|");
            jButton32.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton32MouseClicked(evt);
                }
            });
            getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 140, 60, 40));

            d.setBackground(new java.awt.Color(153, 0, 153));
            d.setForeground(new java.awt.Color(255, 255, 255));
            d.setText("D");
            d.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    dMouseClicked(evt);
                }
            });
            getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 60, 40));

            jButton34.setBackground(new java.awt.Color(255, 0, 0));
            jButton34.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton34.setForeground(new java.awt.Color(255, 255, 255));
            jButton34.setText("capslock");
            jButton34.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton34MouseClicked(evt);
                }
            });
            getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, 40));

            a.setBackground(new java.awt.Color(153, 0, 153));
            a.setForeground(new java.awt.Color(255, 255, 255));
            a.setText("A");
            a.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    aMouseClicked(evt);
                }
            });
            getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 60, 40));

            s.setBackground(new java.awt.Color(153, 0, 153));
            s.setForeground(new java.awt.Color(255, 255, 255));
            s.setText("S");
            s.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    sMouseClicked(evt);
                }
            });
            getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 60, 40));

            j.setBackground(new java.awt.Color(153, 0, 153));
            j.setForeground(new java.awt.Color(255, 255, 255));
            j.setText("J");
            j.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jMouseClicked(evt);
                }
            });
            getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 60, 40));

            f.setBackground(new java.awt.Color(153, 0, 153));
            f.setForeground(new java.awt.Color(255, 255, 255));
            f.setText("F");
            f.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    fMouseClicked(evt);
                }
            });
            f.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    fActionPerformed(evt);
                }
            });
            getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 60, 40));

            g.setBackground(new java.awt.Color(153, 0, 153));
            g.setForeground(new java.awt.Color(255, 255, 255));
            g.setText("G");
            g.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    gMouseClicked(evt);
                }
            });
            getContentPane().add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 60, 40));

            h.setBackground(new java.awt.Color(153, 0, 153));
            h.setForeground(new java.awt.Color(255, 255, 255));
            h.setText("H");
            h.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    hMouseClicked(evt);
                }
            });
            getContentPane().add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 60, 40));

            jButton41.setBackground(new java.awt.Color(0, 255, 0));
            jButton41.setText("'");
            jButton41.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton41MouseClicked(evt);
                }
            });
            getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 60, 40));

            k.setBackground(new java.awt.Color(153, 0, 153));
            k.setForeground(new java.awt.Color(255, 255, 255));
            k.setText("K");
            k.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    kMouseClicked(evt);
                }
            });
            getContentPane().add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 60, 40));

            l.setBackground(new java.awt.Color(153, 0, 153));
            l.setForeground(new java.awt.Color(255, 255, 255));
            l.setText("L");
            l.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lMouseClicked(evt);
                }
            });
            getContentPane().add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 60, 40));

            jButton44.setBackground(new java.awt.Color(0, 255, 0));
            jButton44.setText(";");
            jButton44.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton44MouseClicked(evt);
                }
            });
            getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 60, 40));

            jButton45.setBackground(new java.awt.Color(0, 255, 0));
            jButton45.setText(">");
            jButton45.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton45MouseClicked(evt);
                }
            });
            getContentPane().add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 190, 60, 40));

            jButton46.setBackground(new java.awt.Color(0, 255, 0));
            jButton46.setText("\"");
            jButton46.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton46MouseClicked(evt);
                }
            });
            getContentPane().add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 60, 40));

            jButton47.setBackground(new java.awt.Color(0, 255, 0));
            jButton47.setText("?");
            jButton47.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton47MouseClicked(evt);
                }
            });
            getContentPane().add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 190, 60, 40));

            jButton48.setBackground(new java.awt.Color(0, 255, 0));
            jButton48.setText("<");
            jButton48.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton48MouseClicked(evt);
                }
            });
            getContentPane().add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, 60, 40));

            c.setBackground(new java.awt.Color(153, 0, 153));
            c.setForeground(new java.awt.Color(255, 255, 255));
            c.setText("C");
            c.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    cMouseClicked(evt);
                }
            });
            getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 60, 40));

            jButton50.setBackground(new java.awt.Color(0, 255, 0));
            jButton50.setText("~");
            jButton50.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton50MouseClicked(evt);
                }
            });
            getContentPane().add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, 40));

            z.setBackground(new java.awt.Color(153, 0, 153));
            z.setForeground(new java.awt.Color(255, 255, 255));
            z.setText("Z");
            z.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    zMouseClicked(evt);
                }
            });
            getContentPane().add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 60, 40));

            x.setBackground(new java.awt.Color(153, 0, 153));
            x.setForeground(new java.awt.Color(255, 255, 255));
            x.setText("X");
            x.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    xMouseClicked(evt);
                }
            });
            getContentPane().add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 60, 40));

            m.setBackground(new java.awt.Color(153, 0, 153));
            m.setForeground(new java.awt.Color(255, 255, 255));
            m.setText("M");
            m.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    mMouseClicked(evt);
                }
            });
            getContentPane().add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 60, 40));

            v.setBackground(new java.awt.Color(153, 0, 153));
            v.setForeground(new java.awt.Color(255, 255, 255));
            v.setText("V");
            v.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    vMouseClicked(evt);
                }
            });
            getContentPane().add(v, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 60, 40));

            b.setBackground(new java.awt.Color(153, 0, 153));
            b.setForeground(new java.awt.Color(255, 255, 255));
            b.setText("B");
            b.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    bMouseClicked(evt);
                }
            });
            getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 60, 40));

            n.setBackground(new java.awt.Color(153, 0, 153));
            n.setForeground(new java.awt.Color(255, 255, 255));
            n.setText("N");
            n.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    nMouseClicked(evt);
                }
            });
            getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 60, 40));

            jButton57.setBackground(new java.awt.Color(0, 255, 0));
            jButton57.setText("_");
            jButton57.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton57MouseClicked(evt);
                }
            });
            getContentPane().add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 60, 40));

            jButton58.setBackground(new java.awt.Color(0, 255, 0));
            jButton58.setText(",");
            jButton58.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton58MouseClicked(evt);
                }
            });
            getContentPane().add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 60, 40));

            jButton59.setBackground(new java.awt.Color(0, 255, 0));
            jButton59.setText(".");
            jButton59.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton59MouseClicked(evt);
                }
            });
            getContentPane().add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 60, 40));

            jButton60.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton60MouseClicked(evt);
                }
            });
            getContentPane().add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 60, 40));

            jButton61.setBackground(new java.awt.Color(0, 255, 0));
            jButton61.setText("$");
            jButton61.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton61MouseClicked(evt);
                }
            });
            getContentPane().add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, 60, 40));

            jButton62.setBackground(new java.awt.Color(0, 255, 0));
            jButton62.setText("!");
            jButton62.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton62MouseClicked(evt);
                }
            });
            getContentPane().add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 60, 40));

            jButton63.setBackground(new java.awt.Color(0, 255, 0));
            jButton63.setText("@");
            jButton63.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton63MouseClicked(evt);
                }
            });
            getContentPane().add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 60, 40));

            jButton64.setBackground(new java.awt.Color(0, 255, 0));
            jButton64.setText("#");
            jButton64.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton64MouseClicked(evt);
                }
            });
            getContentPane().add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 60, 40));

            jButton65.setBackground(new java.awt.Color(0, 255, 0));
            jButton65.setText("™");
            jButton65.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton65MouseClicked(evt);
                }
            });
            getContentPane().add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 60, 40));

            jButton66.setBackground(new java.awt.Color(0, 255, 0));
            jButton66.setText("¼");
            jButton66.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton66MouseClicked(evt);
                }
            });
            getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 60, 40));

            jButton67.setBackground(new java.awt.Color(0, 255, 0));
            jButton67.setText("½");
            jButton67.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton67MouseClicked(evt);
                }
            });
            getContentPane().add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 60, 40));

            jButton68.setBackground(new java.awt.Color(0, 255, 0));
            jButton68.setText("‰");
            jButton68.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton68MouseClicked(evt);
                }
            });
            getContentPane().add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 60, 40));

            jButton69.setBackground(new java.awt.Color(0, 255, 0));
            jButton69.setText("}");
            jButton69.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton69MouseClicked(evt);
                }
            });
            getContentPane().add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 60, 40));

            jButton70.setBackground(new java.awt.Color(0, 255, 0));
            jButton70.setText("≈");
            jButton70.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton70MouseClicked(evt);
                }
            });
            getContentPane().add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 60, 40));

            jButton71.setBackground(new java.awt.Color(0, 255, 0));
            jButton71.setText("±");
            jButton71.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton71MouseClicked(evt);
                }
            });
            getContentPane().add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 60, 40));

            jButton72.setBackground(new java.awt.Color(0, 255, 0));
            jButton72.setText("{");
            jButton72.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton72MouseClicked(evt);
                }
            });
            getContentPane().add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 60, 40));

            jButton73.setBackground(new java.awt.Color(0, 255, 0));
            jButton73.setText("(");
            jButton73.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton73MouseClicked(evt);
                }
            });
            getContentPane().add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 60, 40));

            jButton74.setBackground(new java.awt.Color(0, 255, 0));
            jButton74.setText("%");
            jButton74.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton74MouseClicked(evt);
                }
            });
            getContentPane().add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 60, 40));

            jButton75.setBackground(new java.awt.Color(0, 255, 0));
            jButton75.setText("^");
            jButton75.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton75MouseClicked(evt);
                }
            });
            getContentPane().add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 60, 40));

            jButton76.setBackground(new java.awt.Color(0, 255, 0));
            jButton76.setText("&");
            jButton76.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton76MouseClicked(evt);
                }
            });
            getContentPane().add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 60, 40));

            jButton77.setBackground(new java.awt.Color(0, 255, 0));
            jButton77.setText("£");
            jButton77.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton77MouseClicked(evt);
                }
            });
            getContentPane().add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 290, 60, 40));

            jButton78.setBackground(new java.awt.Color(0, 255, 0));
            jButton78.setText(")");
            jButton78.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton78MouseClicked(evt);
                }
            });
            getContentPane().add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 60, 40));

            jButton79.setBackground(new java.awt.Color(0, 255, 0));
            jButton79.setText("®");
            jButton79.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton79MouseClicked(evt);
                }
            });
            getContentPane().add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 60, 40));

            jButton80.setBackground(new java.awt.Color(0, 255, 0));
            jButton80.setText("©");
            jButton80.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton80MouseClicked(evt);
                }
            });
            getContentPane().add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, 60, 40));

            jButton81.setBackground(new java.awt.Color(0, 255, 0));
            jButton81.setText("Ω");
            jButton81.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton81MouseClicked(evt);
                }
            });
            getContentPane().add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 60, 40));

            jButton82.setBackground(new java.awt.Color(0, 255, 0));
            jButton82.setText("µ");
            jButton82.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton82MouseClicked(evt);
                }
            });
            getContentPane().add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 60, 40));

            jButton83.setBackground(new java.awt.Color(0, 255, 0));
            jButton83.setText("φ");
            jButton83.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton83MouseClicked(evt);
                }
            });
            getContentPane().add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 60, 40));

            jButton84.setBackground(new java.awt.Color(0, 255, 0));
            jButton84.setText("δ");
            jButton84.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton84MouseClicked(evt);
                }
            });
            getContentPane().add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 60, 40));

            jButton85.setBackground(new java.awt.Color(0, 255, 0));
            jButton85.setText("♀");
            jButton85.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton85MouseClicked(evt);
                }
            });
            getContentPane().add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 60, 40));

            jButton86.setBackground(new java.awt.Color(0, 255, 0));
            jButton86.setText("Θ");
            jButton86.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton86MouseClicked(evt);
                }
            });
            getContentPane().add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 60, 40));

            jButton87.setBackground(new java.awt.Color(0, 255, 0));
            jButton87.setText("♫");
            jButton87.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton87MouseClicked(evt);
                }
            });
            getContentPane().add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 60, 40));

            jButton88.setBackground(new java.awt.Color(0, 255, 0));
            jButton88.setText("♪");
            jButton88.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton88MouseClicked(evt);
                }
            });
            getContentPane().add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 60, 40));

            jButton89.setBackground(new java.awt.Color(0, 255, 0));
            jButton89.setText("♦");
            jButton89.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton89MouseClicked(evt);
                }
            });
            getContentPane().add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 60, 40));

            jButton90.setBackground(new java.awt.Color(0, 255, 0));
            jButton90.setText("♂");
            jButton90.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton90MouseClicked(evt);
                }
            });
            getContentPane().add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 60, 40));

            jButton91.setBackground(new java.awt.Color(0, 255, 0));
            jButton91.setText("♠");
            jButton91.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton91MouseClicked(evt);
                }
            });
            getContentPane().add(jButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 60, 40));

            jButton92.setBackground(new java.awt.Color(0, 255, 0));
            jButton92.setText("♣");
            jButton92.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton92MouseClicked(evt);
                }
            });
            getContentPane().add(jButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 60, 40));

            jButton93.setBackground(new java.awt.Color(0, 255, 0));
            jButton93.setText("€");
            jButton93.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton93MouseClicked(evt);
                }
            });
            getContentPane().add(jButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 340, 60, 40));

            jButton94.setBackground(new java.awt.Color(0, 255, 0));
            jButton94.setText("♥");
            jButton94.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton94MouseClicked(evt);
                }
            });
            getContentPane().add(jButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, 60, 40));

            jButton95.setBackground(new java.awt.Color(0, 255, 0));
            jButton95.setText("⦝");
            jButton95.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton95MouseClicked(evt);
                }
            });
            getContentPane().add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 60, 40));

            jButton96.setBackground(new java.awt.Color(0, 255, 0));
            jButton96.setText("⊾");
            jButton96.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton96MouseClicked(evt);
                }
            });
            getContentPane().add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 340, 60, 40));

            capslockOznaka.setText("0");
            getContentPane().add(capslockOznaka, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 20, 20));
            getContentPane().add(capslockOznaka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 20, 20));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      this.setSize(1169, 432);
    }//GEN-LAST:event_formWindowActivated

    private void jButton34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton34MouseClicked
        if (capslockOznaka1.getText().isEmpty()){
        capslockOznaka1.setText("I");
        capslockOznaka.setText("");
        q.setText("q");
        w.setText("w");
        e.setText("e");
        r.setText("r");
        t.setText("t");
        y.setText("y");
        u.setText("u");
        i.setText("i");
        o.setText("o");
        p.setText("p");
        a.setText("a");
        s.setText("s");
        d.setText("d");
        f.setText("f");
        g.setText("g");
        h.setText("h"); 
        j.setText("j");
        k.setText("k");
        l.setText("l");
        z.setText("z");
        x.setText("x");
        c.setText("c");
        v.setText("v");
        b.setText("b");
        n.setText("n");
        m.setText("m");
        }
        else if(capslockOznaka1.getText().equals("I")){
       capslockOznaka.setText("0");
       capslockOznaka1.setText("");
       q.setText("Q");
        w.setText("W");
        e.setText("E");
        r.setText("R");
        t.setText("T");
        y.setText("Y");
        u.setText("U");
        i.setText("I");
        o.setText("O");
        p.setText("P");
        a.setText("A");
        s.setText("S");
        d.setText("D");
        f.setText("F");
        g.setText("G");
        h.setText("H"); 
        j.setText("J");
        k.setText("K");
        l.setText("L");
        z.setText("Z");
        x.setText("X");
        c.setText("C");
        v.setText("V");
        b.setText("B");
        n.setText("N");
        m.setText("M");
        }
        
        
        
    }//GEN-LAST:event_jButton34MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        display.setText(display.getText()+"\t");
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        display.setText(display.getText()+"1");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
       display.setText(display.getText()+"2");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       display.setText(display.getText()+"3");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
       display.setText(display.getText()+"4");
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        display.setText(display.getText()+"5");
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
      display.setText(display.getText()+"6");
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
       display.setText(display.getText()+"7");
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
       display.setText(display.getText()+"8");
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
       display.setText(display.getText()+"9");
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
       display.setText(display.getText()+"0");
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        display.setText(display.getText()+"=");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
     display.setText(display.getText()+"-");
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        display.setText(display.getText()+"+");
    }//GEN-LAST:event_jButton15MouseClicked

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        display.setText(display.getText()+"*");
    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        display.setText(display.getText()+"/");
    }//GEN-LAST:event_jButton13MouseClicked

    private void qMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qMouseClicked
    display.setText(display.getText()+q.getText());     
    }//GEN-LAST:event_qMouseClicked

    private void wMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wMouseClicked
        display.setText(display.getText()+w.getText());
    }//GEN-LAST:event_wMouseClicked

    private void eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eMouseClicked
        display.setText(display.getText()+e.getText());
    }//GEN-LAST:event_eMouseClicked

    private void rMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rMouseClicked
       display.setText(display.getText()+r.getText());
    }//GEN-LAST:event_rMouseClicked

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
        display.setText(display.getText()+t.getText());
    }//GEN-LAST:event_tMouseClicked

    private void yMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yMouseClicked
        display.setText(display.getText()+y.getText());
    }//GEN-LAST:event_yMouseClicked

    private void uMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uMouseClicked
      display.setText(display.getText()+u.getText());
    }//GEN-LAST:event_uMouseClicked

    private void iMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMouseClicked
       display.setText(display.getText()+i.getText());
    }//GEN-LAST:event_iMouseClicked

    private void oMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oMouseClicked
      display.setText(display.getText()+o.getText());
    }//GEN-LAST:event_oMouseClicked

    private void pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseClicked
        display.setText(display.getText()+p.getText());
    }//GEN-LAST:event_pMouseClicked

    private void jButton25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton25MouseClicked
        display.setText(display.getText()+"[");
    }//GEN-LAST:event_jButton25MouseClicked

    private void jButton30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton30MouseClicked
        display.setText(display.getText()+"]");
    }//GEN-LAST:event_jButton30MouseClicked

    private void jButton31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton31MouseClicked
        display.setText(display.getText()+"\\");
    }//GEN-LAST:event_jButton31MouseClicked

    private void jButton32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton32MouseClicked
       display.setText(display.getText()+"|");
    }//GEN-LAST:event_jButton32MouseClicked

    private void jButton29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton29MouseClicked
        display.setText(display.getText()+"*");
    }//GEN-LAST:event_jButton29MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        display.setText(display.getText()+"`");
    }//GEN-LAST:event_jButton2MouseClicked

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
        display.setText(display.getText()+a.getText());
    }//GEN-LAST:event_aMouseClicked

    private void sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMouseClicked
        display.setText(display.getText()+s.getText());
    }//GEN-LAST:event_sMouseClicked

    private void dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dMouseClicked
        display.setText(display.getText()+d.getText());
    }//GEN-LAST:event_dMouseClicked

    private void fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fMouseClicked
        display.setText(display.getText()+f.getText());
    }//GEN-LAST:event_fMouseClicked

    private void gMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gMouseClicked
       display.setText(display.getText()+g.getText());
    }//GEN-LAST:event_gMouseClicked

    private void hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMouseClicked
        display.setText(display.getText()+h.getText());
    }//GEN-LAST:event_hMouseClicked

    private void jMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMouseClicked
       display.setText(display.getText()+j.getText());
    }//GEN-LAST:event_jMouseClicked

    private void kMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kMouseClicked
        display.setText(display.getText()+k.getText());
    }//GEN-LAST:event_kMouseClicked

    private void lMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lMouseClicked
       display.setText(display.getText()+l.getText());
    }//GEN-LAST:event_lMouseClicked

    private void jButton44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton44MouseClicked
        display.setText(display.getText()+";");
    }//GEN-LAST:event_jButton44MouseClicked

    private void jButton41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton41MouseClicked
        display.setText(display.getText()+"'");
    }//GEN-LAST:event_jButton41MouseClicked

    private void jButton46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton46MouseClicked
       display.setText(display.getText()+"\"");
    }//GEN-LAST:event_jButton46MouseClicked

    private void jButton47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton47MouseClicked
       display.setText(display.getText()+"?");
    }//GEN-LAST:event_jButton47MouseClicked

    private void jButton48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton48MouseClicked
       display.setText(display.getText()+"<");
    }//GEN-LAST:event_jButton48MouseClicked

    private void jButton45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton45MouseClicked
        display.setText(display.getText()+">");
    }//GEN-LAST:event_jButton45MouseClicked

    private void jButton50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton50MouseClicked
        display.setText(display.getText()+"~");
    }//GEN-LAST:event_jButton50MouseClicked

    private void zMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zMouseClicked
       display.setText(display.getText()+z.getText());
    }//GEN-LAST:event_zMouseClicked

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
       display.setText(display.getText()+x.getText());
    }//GEN-LAST:event_xMouseClicked

    private void cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseClicked
        display.setText(display.getText()+c.getText());
    }//GEN-LAST:event_cMouseClicked

    private void vMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMouseClicked
       display.setText(display.getText()+v.getText());
    }//GEN-LAST:event_vMouseClicked

    private void bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMouseClicked
        display.setText(display.getText()+b.getText());
    }//GEN-LAST:event_bMouseClicked

    private void nMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nMouseClicked
        display.setText(display.getText()+n.getText());
    }//GEN-LAST:event_nMouseClicked

    private void mMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMouseClicked
       display.setText(display.getText()+m.getText());
    }//GEN-LAST:event_mMouseClicked

    private void jButton60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton60MouseClicked
       display.setText(display.getText()+" ");
    }//GEN-LAST:event_jButton60MouseClicked

    private void jButton58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton58MouseClicked
        display.setText(display.getText()+",");
    }//GEN-LAST:event_jButton58MouseClicked

    private void jButton59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton59MouseClicked
        display.setText(display.getText()+".");
    }//GEN-LAST:event_jButton59MouseClicked

    private void jButton57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton57MouseClicked
       display.setText(display.getText()+"_");
    }//GEN-LAST:event_jButton57MouseClicked

    private void jButton62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton62MouseClicked
       display.setText(display.getText()+"!");
    }//GEN-LAST:event_jButton62MouseClicked

    private void jButton63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton63MouseClicked
       display.setText(display.getText()+"@");
    }//GEN-LAST:event_jButton63MouseClicked

    private void jButton64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton64MouseClicked
        display.setText(display.getText()+"#");
    }//GEN-LAST:event_jButton64MouseClicked

    private void jButton61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton61MouseClicked
       display.setText(display.getText()+"$");
    }//GEN-LAST:event_jButton61MouseClicked

    private void jButton66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton66MouseClicked
        display.setText(display.getText()+"¼");
    }//GEN-LAST:event_jButton66MouseClicked

    private void jButton67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton67MouseClicked
        display.setText(display.getText()+"½");
    }//GEN-LAST:event_jButton67MouseClicked

    private void jButton68MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton68MouseClicked
         display.setText(display.getText()+"‰");
    }//GEN-LAST:event_jButton68MouseClicked

    private void jButton65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton65MouseClicked
       display.setText(display.getText()+"™");
    }//GEN-LAST:event_jButton65MouseClicked

    private void jButton70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton70MouseClicked
       display.setText(display.getText()+"≈");
    }//GEN-LAST:event_jButton70MouseClicked

    private void jButton71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton71MouseClicked
        display.setText(display.getText()+"±");
    }//GEN-LAST:event_jButton71MouseClicked

    private void jButton72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton72MouseClicked
        display.setText(display.getText()+"{");
    }//GEN-LAST:event_jButton72MouseClicked

    private void jButton69MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton69MouseClicked
       display.setText(display.getText()+"}");
    }//GEN-LAST:event_jButton69MouseClicked

    private void jButton74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton74MouseClicked
       display.setText(display.getText()+"%");
    }//GEN-LAST:event_jButton74MouseClicked

    private void jButton75MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton75MouseClicked
        display.setText(display.getText()+"^");
    }//GEN-LAST:event_jButton75MouseClicked

    private void jButton76MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton76MouseClicked
        display.setText(display.getText()+"&");
    }//GEN-LAST:event_jButton76MouseClicked

    private void jButton73MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton73MouseClicked
       display.setText(display.getText()+"(");
    }//GEN-LAST:event_jButton73MouseClicked

    private void jButton78MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton78MouseClicked
       display.setText(display.getText()+")");
    }//GEN-LAST:event_jButton78MouseClicked

    private void jButton79MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton79MouseClicked
       display.setText(display.getText()+"®");
    }//GEN-LAST:event_jButton79MouseClicked

    private void jButton80MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton80MouseClicked
          display.setText(display.getText()+"©");
    }//GEN-LAST:event_jButton80MouseClicked

    private void jButton77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton77MouseClicked
        display.setText(display.getText()+"£");
    }//GEN-LAST:event_jButton77MouseClicked

    private void jButton82MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton82MouseClicked
       display.setText(display.getText()+"µ"); 
    }//GEN-LAST:event_jButton82MouseClicked

    private void jButton83MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton83MouseClicked
       display.setText(display.getText()+"φ");  
    }//GEN-LAST:event_jButton83MouseClicked

    private void jButton84MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton84MouseClicked
        display.setText(display.getText()+"δ");  
    }//GEN-LAST:event_jButton84MouseClicked

    private void jButton81MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton81MouseClicked
         display.setText(display.getText()+"Ω");  
    }//GEN-LAST:event_jButton81MouseClicked

    private void jButton86MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton86MouseClicked
        display.setText(display.getText()+"Θ");  
    }//GEN-LAST:event_jButton86MouseClicked

    private void jButton87MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton87MouseClicked
       display.setText(display.getText()+"♫"); 
    }//GEN-LAST:event_jButton87MouseClicked

    private void jButton88MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton88MouseClicked
        display.setText(display.getText()+"♪"); 
    }//GEN-LAST:event_jButton88MouseClicked

    private void jButton85MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton85MouseClicked
        display.setText(display.getText()+"♀"); 
    }//GEN-LAST:event_jButton85MouseClicked

    private void jButton90MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton90MouseClicked
        display.setText(display.getText()+"♂"); 
    }//GEN-LAST:event_jButton90MouseClicked

    private void jButton91MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton91MouseClicked
       display.setText(display.getText()+"♠"); 
    }//GEN-LAST:event_jButton91MouseClicked

    private void jButton92MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton92MouseClicked
       display.setText(display.getText()+"♣"); 
    }//GEN-LAST:event_jButton92MouseClicked

    private void jButton89MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton89MouseClicked
        display.setText(display.getText()+"♦"); 
    }//GEN-LAST:event_jButton89MouseClicked

    private void jButton94MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton94MouseClicked
        display.setText(display.getText()+"♥");
    }//GEN-LAST:event_jButton94MouseClicked

    private void jButton95MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton95MouseClicked
       display.setText(display.getText()+"⦝");
    }//GEN-LAST:event_jButton95MouseClicked

    private void jButton96MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton96MouseClicked
        display.setText(display.getText()+"⊾"); 
    }//GEN-LAST:event_jButton96MouseClicked

    private void jButton93MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton93MouseClicked
        display.setText(display.getText()+"€"); 
    }//GEN-LAST:event_jButton93MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tastatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tastatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tastatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tastatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tastatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JLabel capslockOznaka;
    private javax.swing.JLabel capslockOznaka1;
    private javax.swing.JButton d;
    private javax.swing.JTextField display;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton s;
    private javax.swing.JButton t;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JButton w;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    // End of variables declaration//GEN-END:variables
}
